% Copyright (C) 2016 Siu-Kei Muk, Jason Bolito
% All rights reserved.
%
% This software may be modified and distributed under the terms
% of the BSD license.  See the LICENSE file for details.

rootDirectory = '../char_db_50';
classes = {'0','1','2','3','4','5','6','7','8','9',...
           'A','B','C','D','E','F','G','H','I','J',...
           'K','M','N','L','O','P','Q','R','S','T',...
           'U','V','W','X','Y','Z'};

imds_char = imageDatastore(fullfile(rootDirectory,classes),'LabelSource','foldernames');

cnnarch = [...
    imageInputLayer([50, 50, 1]),...
    convolution2dLayer(3,16, 'Padding', [5 5]),...
    reluLayer(),...
    maxPooling2dLayer(2,'Stride',2),...
    dropoutLayer(0.2),...
    convolution2dLayer(3,32),...
    reluLayer(),...
    maxPooling2dLayer(2,'Stride',2),...
    dropoutLayer(0.3),...
    convolution2dLayer(3, 64),...
    reluLayer(),...
    dropoutLayer(0.3),...
    fullyConnectedLayer(200),...
    reluLayer(),...
    dropoutLayer(),...
    fullyConnectedLayer(36),...
    softmaxLayer(),...
    classificationLayer()];

opts = trainingOptions('sgdm','MaxEpochs', 100, 'MiniBatchSize', 128, 'LearnRateSchedule','piecewise', 'LearnRateDropPeriod', 40);
